reading and writing registers
Wenzel/libmicrovmi pull request #90
Opened 2020-07-17 14:22 UTC by arnabcs17b006

Please do not merge. It is leaking memory

2020-07-19 10:09 UTC, rageagainsthepc commented on src/driver/xen.rs
> +        unsafe {
You should never use unsafe blocks in libmicrovmi. The whole point of having crates like `xenctrl` or `kvmi` is to provide safe bindings. Anything that is unsafe should be done in there.

2020-08-19 23:07 UTC, Wenzel commented
@arnabcs17b006 please rebase

2020-08-19 23:28 UTC, Wenzel requested changes

2020-08-19 23:28 UTC, Wenzel commented on examples/regs-dump.rs
> +    let total_vcpu_count: u16 = 1;
why is this value hardcoded to 1 ?

2020-08-19 23:28 UTC, Wenzel commented on src/driver/kvm.rs
> -            ldt: sregs.ldt.into(),
why are you removing these values from the KVM driver ???

2020-08-19 23:28 UTC, Wenzel commented on src/driver/xen.rs
> -                selector: 0,
What happened to ldt ?

2020-08-19 23:28 UTC, Wenzel commented
@arnabcs17b006 also please rebase

2020-08-26 21:55 UTC, Wenzel requested changes

2020-08-26 21:55 UTC, Wenzel commented on examples/regs-dump.rs
> +    //let total_vcpu_count: u16 = drv.get_vcpu_count().expect("Failed to get vcpu count");
which is this code commented ?
you replace an expect by an unwrap.

2020-12-16 23:01 UTC, closed without merging